services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyPlatform\:
        resource: '../../{Controller,Form,Repository,Service}'

    Wexample\SymfonyPlatform\Api\Normalizer\:
        resource: '../../Api/Normalizer/*'
        tags: ['serializer.normalizer']
